#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::redundant_static_lifetimes)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
include!(concat!(env!("OUT_DIR"), "/bindings_iids.rs"));

pub const IID_IUnknown: GUID = GUID {
    Data1: 0u32,
    Data2: 0u16,
    Data3: 0u16,
    Data4: [192u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 70u8],
};

#[cfg(test)]
mod tests {
    use super::*;

    // We test linking of symbols that are not generated by bindgen
    // We use `#[test]` and `dbg!` to force linking

    #[test]
    #[ignore]
    fn __iids_linked() {
        let _ = dbg!(unsafe { IID_IAIMPConfig });
    }

    #[test]
    #[ignore]
    fn __util_linked() {
        let _ = dbg!(unsafe { GetSelfPointer() });
    }
}
