[package]
name = "polygon"
version = "0.1.0"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
edition = "2018"

[dependencies]
iaimp = { path = "../../iaimp" }
aimp = { path = "../.." }
thiserror = "1.0.20"
http = "0.2.1"

[lib]
crate-type = ["cdylib"]
