[package]
name = "aimp-sys"
version = "0.1.0"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.53"
cc = "1.0.54"
clang = { version = "0.23.0", features = ["runtime"] }
